// Client-side cover-letter PDF (jsPDF) — shared by the Apply flow and the cover-letter pages.

export interface LetterPdfInput {
  letter: string
  name?: string
  contact?: string
  jobTitle?: string
  employer?: string
  filename?: string
}

export async function downloadLetterPdf({ letter, name, contact, jobTitle, employer, filename }: LetterPdfInput): Promise<void> {
  const { default: jsPDF } = await import('jspdf')
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const W = 210
  const margin = 22
  const contentW = W - margin * 2

  doc.setFillColor(4, 44, 83)
  doc.rect(0, 0, W, 12, 'F')
  doc.setFillColor(55, 138, 221)
  doc.rect(0, 10, W, 2, 'F')

  let y = 24
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.setTextColor(4, 44, 83)
  doc.text(name || 'Cover Letter', margin, y)
  y += 6

  if (contact) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(107, 124, 147)
    doc.text(contact, margin, y)
    y += 5
  }

  if (jobTitle || employer) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(107, 124, 147)
    doc.text([employer, jobTitle].filter(Boolean).join(' - '), margin, y)
    y += 5
  }

  doc.setDrawColor(220, 228, 238)
  doc.setLineWidth(0.4)
  doc.line(margin, y, W - margin, y)
  y += 16

  const paragraphs = letter.split('\n').filter(p => p.trim() !== '')
  paragraphs.forEach((para, i) => {
    const isFirst = i === 0
    const isLast = i === paragraphs.length - 1
    if (y > 260) { doc.addPage(); y = 20 }
    doc.setFont('helvetica', isFirst || isLast ? 'bold' : 'normal')
    doc.setFontSize(10.5)
    doc.setTextColor(26, 35, 50)
    const lines = doc.splitTextToSize(para, contentW)
    doc.text(lines, margin, y)
    y += lines.length * 6 + 5
  })

  const pageCount = (doc as unknown as { internal: { getNumberOfPages: () => number } }).internal.getNumberOfPages()
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p)
    doc.setFillColor(248, 250, 252)
    doc.rect(0, 285, W, 12, 'F')
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    doc.setTextColor(143, 163, 184)
    doc.text('Generated by Job-Lens AI', margin, 292)
    doc.text(`Page ${p} of ${pageCount}`, W - margin, 292, { align: 'right' })
  }

  doc.save(filename || `CoverLetter_${(employer || 'JobLens').replace(/[^a-zA-Z0-9]/g, '_')}.pdf`)
}
