'use client'
// EU AI Act Art. 50 — transparency obligation.
// Shown on every page that presents AI-generated output to users.

interface Props {
  lang?: 'DE' | 'EN'
}

export function AiDisclosureNotice({ lang = 'EN' }: Props) {
  const text = lang === 'DE'
    ? 'Diese Ergebnisse wurden von einem KI-System (Claude von Anthropic) generiert und dienen ausschließlich als Orientierung. Sie können ungenau sein. Bitte prüfe alle Inhalte, bevor du sie in einer Bewerbung verwendest.'
    : 'These results are generated by an AI system (Claude by Anthropic) and are intended as guidance only. They may not be accurate. Please review all content before using it in a job application.'

  return (
    <div style={{
      display: 'flex', alignItems: 'flex-start', gap: 10,
      padding: '10px 14px', borderRadius: 8,
      background: 'rgba(55,138,221,0.06)', border: '1px solid rgba(55,138,221,0.18)',
      fontSize: 12, color: '#5a7a9c', lineHeight: 1.6, marginTop: 12,
    }}>
      <span style={{ fontSize: 14, flexShrink: 0 }}>🤖</span>
      <span>{text}</span>
    </div>
  )
}
